# Generated by Django 4.1.2 on 2022-10-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0005_delete_assets'),
        ('cryptocurrency', '0004_rename_address_subscription_addresssubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_keys.apikey')),
                ('cryptocurrency_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.cryptocurrency')),
            ],
        ),
    ]
