# Generated by Django 4.1.3 on 2022-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
