# Generated by Django 4.1.3 on 2022-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_address_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
