# Generated by Django 4.1.1 on 2022-10-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_transaction_expiration_datetime'),
        ('digital_currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Digital_Currency',
            new_name='DigitalCurrency',
        ),
    ]
