# Generated by Django 4.1.1 on 2022-10-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_currency', '0002_rename_digital_currency_digitalcurrency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalcurrency',
            old_name='digital_currency_name',
            new_name='name',
        ),
    ]
