# Generated by Django 4.1.1 on 2022-09-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_business_user_id_delete_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='state',
            field=models.CharField(default='ALLOW', max_length=15),
            preserve_default=False,
        ),
    ]
