# Generated by Django 4.1.1 on 2022-09-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='state',
            new_name='status',
        ),
    ]
