# Generated by Django 4.1.2 on 2022-11-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_state_country_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='security_pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
