# Generated by Django 4.1.3 on 2022-11-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_cryptosharecredit_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='random_password',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
