# Generated by Django 3.2.16 on 2023-06-02 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_account_birthdate_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insividual_Account',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('identity', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('cadula', models.CharField(max_length=200)),
                ('birthdate', models.DateField(null=True)),
                ('cryptosharecredit_linked', models.BooleanField(default=False)),
                ('cryptosharecredit_email', models.EmailField(max_length=254, null=True)),
                ('cryptosharecredit_username', models.CharField(max_length=30, null=True)),
                ('security_pin', models.CharField(max_length=6, null=True)),
                ('random_password', models.CharField(max_length=16, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=15)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
