# Generated by Django 4.1.1 on 2022-09-25 05:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryptocurrency', '0001_initial'),
        ('api_keys', '0003_assets_cryptocurrency_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat_Currency',
            fields=[
                ('fiat_currency_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fiat_currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=12)),
                ('fiat_currency_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('address_refund', models.CharField(max_length=100, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.address')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_keys.api_key')),
                ('fiat_currency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.fiat_currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Outs',
            fields=[
                ('transaction_ins_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('address_out', models.CharField(max_length=100)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('completed_datetime', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.address')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Ins',
            fields=[
                ('transaction_ins_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('completed_datetime', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.address')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Book',
            fields=[
                ('registry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=5)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction')),
                ('transaction_ins_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction_ins')),
                ('transaction_outs_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction_outs')),
            ],
        ),
    ]
