# Generated by Django 4.1.1 on 2022-09-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_state_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
