# Generated by Django 4.1.1 on 2022-09-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client_telephone',
            new_name='client_phone',
        ),
    ]
