# Generated by Django 4.1.1 on 2022-09-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_client_telephone_transaction_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
