# Generated by Django 4.1.1 on 2022-09-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cryptocurrency_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
