# Generated by Django 4.1.1 on 2022-09-29 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 1, 42, 1, 62954, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
