# Generated by Django 4.1.1 on 2022-09-29 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 3, 37, 45, 214459, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
