# Generated by Django 4.1.1 on 2022-10-05 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transaction_expiration_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 1, 36, 37, 140488, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
