# Generated by Django 4.1.1 on 2022-10-05 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 1, 46, 15, 659581, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
