# Generated by Django 4.1.1 on 2022-10-05 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_rename_address_subscription_addresssubscription'),
        ('transactions', '0016_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_Book',
            new_name='TransactionBook',
        ),
        migrations.RenameModel(
            old_name='Transaction_Ins',
            new_name='TransactionIns',
        ),
        migrations.RenameModel(
            old_name='Transaction_Outs',
            new_name='TransactionOuts',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 2, 27, 37, 208848, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
