# Generated by Django 4.1.1 on 2022-10-09 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_rename_transaction_book_transactionbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cryptocurrency_amount_received',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 1, 46, 44, 380228, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
