# Generated by Django 4.1.2 on 2022-10-12 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transaction_cryptocurrency_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 2, 35, 51, 689042, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transactionouts',
            name='address_out',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
