# Generated by Django 4.1.2 on 2022-10-16 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 0, 59, 1, 458798, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
