# Generated by Django 4.1.2 on 2022-10-16 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cryptocurrency_amount_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 3, 47, 31, 615534, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
