# Generated by Django 4.1.2 on 2022-10-25 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_transaction_cryptocurrency_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 0, 3, 13, 767382, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
