# Generated by Django 4.1.2 on 2022-10-25 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_transaction_withdrawal_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 0, 13, 3, 271545, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
