# Generated by Django 4.1.2 on 2022-11-01 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 1, 34, 10, 325350, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
