# Generated by Django 4.1.2 on 2022-11-05 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 5, 17, 51, 561244, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
