# Generated by Django 4.1.2 on 2022-11-07 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 2, 21, 4, 283029, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
