# Generated by Django 4.1.2 on 2022-11-12 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0005_delete_assets'),
        ('transactions', '0027_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 4, 31, 58, 631724, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='AutomatedTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=12)),
                ('frecuency', models.CharField(max_length=7)),
                ('scheduled_day', models.CharField(max_length=12)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_event_datetime', models.DateTimeField(null=True)),
                ('next_event_datetime', models.DateTimeField(null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_keys.apikey')),
            ],
        ),
    ]
