# Generated by Django 4.1.2 on 2022-11-12 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_alter_transaction_expiration_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtransaction',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 4, 47, 5, 7033, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
