# Generated by Django 4.1.2 on 2022-11-12 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0007_staticaddress'),
        ('transactions', '0030_automatedtransaction_cryptocurrency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtransaction',
            name='funds_source_address_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.staticaddress'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 21, 33, 47, 904217, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
