# Generated by Django 4.1.2 on 2022-11-12 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_alter_automatedtransaction_funds_source_address_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtransaction',
            name='client_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='automatedtransaction',
            name='client_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='automatedtransaction',
            name='cryptocurrency_id_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='automatedtransaction',
            name='receiver_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 23, 26, 57, 359458, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
