# Generated by Django 4.1.2 on 2022-11-12 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_automatedtransaction_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 23, 42, 55, 362719, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
