# Generated by Django 4.1.3 on 2022-11-13 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 1, 27, 52, 776277, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
