# Generated by Django 4.1.3 on 2022-11-13 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtransaction',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 1, 40, 25, 180387, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
