# Generated by Django 4.1.3 on 2022-11-19 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_alter_automatedtransaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 5, 22, 59, 492855, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
