# Generated by Django 4.1.3 on 2022-12-01 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_alter_transaction_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 2, 46, 45, 48362, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
