# Generated by Django 4.1.1 on 2022-09-24 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('accounts', '0003_remove_business_user_id_delete_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Key',
            fields=[
                ('api_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('business_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
