# Generated by Django 4.1.1 on 2022-10-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_transaction_expiration_datetime'),
        ('cryptocurrency', '0004_rename_address_subscription_addresssubscription'),
        ('accounts', '0005_rename_state_country_status'),
        ('businesses', '0001_initial'),
        ('api_keys', '0003_assets_cryptocurrency_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api_Key',
            new_name='ApiKey',
        ),
    ]
