# Generated by Django 4.1.2 on 2022-10-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0004_rename_api_key_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
