# Generated by Django 3.2.16 on 2023-06-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_is_main'),
        ('accounts', '0011_insividual_account'),
        ('api_keys', '0005_delete_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey_individual',
            fields=[
                ('api_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('business_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.insividual_account')),
            ],
        ),
    ]
