# Generated by Django 4.1.1 on 2022-09-25 04:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0002_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('blockchain_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('network_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('cryptocurrency_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('blockchain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.blockchain')),
                ('network_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.network')),
            ],
        ),
        migrations.CreateModel(
            name='Address_Subscription',
            fields=[
                ('subscription_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=40)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('callback_url', models.URLField()),
                ('blockchain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.blockchain')),
                ('network_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.network')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_keys.api_key')),
                ('cryptocurrency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptocurrency.cryptocurrency')),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptocurrency.address_subscription')),
            ],
        ),
    ]
