# Generated by Django 4.1.1 on 2022-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_cryptocurrency_coingecko_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
