# Generated by Django 4.1.2 on 2022-10-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_rename_address_subscription_addresssubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='cryptoapis_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
