# Generated by Django 4.1.2 on 2022-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0005_cryptocurrency_cryptoapis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='extra_data',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
