# Generated by Django 4.1.2 on 2022-11-12 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0006_cryptocurrency_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAddress',
            fields=[
                ('static_address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=15)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.address')),
            ],
        ),
    ]
