# Generated by Django 4.1.3 on 2022-11-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0007_staticaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticaddress',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
