# Generated by Django 4.1.3 on 2022-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0008_alter_staticaddress_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticaddress',
            name='type',
            field=models.CharField(max_length=25),
        ),
    ]
